/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_redes;

import java.awt.Color;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
        
public class Vista extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    String Type;
    String ruta_archivo;
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_trama_analizada = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_s_trama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JPanel();
        txt_agregar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_mac_destino = new javax.swing.JLabel();
        txt_mac_origen = new javax.swing.JLabel();
        txt_ethertype = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ip_origen = new javax.swing.JLabel();
        txt_ip_destino = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_puerto_origen = new javax.swing.JLabel();
        txt_puerto_destino = new javax.swing.JLabel();
        txt_protocolo = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_ttl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_procesar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_cerrar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_nombre_archivo = new javax.swing.JLabel();
        txt_error_trama = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_c_trama = new javax.swing.JTextPane();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_id_destino = new javax.swing.JLabel();
        txt_id_origen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setText("Trama Analizada:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, 33));

        txt_trama_analizada.setBackground(new java.awt.Color(140, 180, 220));
        txt_trama_analizada.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_trama_analizada.setText("N/D");
        txt_trama_analizada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 159, 199)));
        jPanel1.add(txt_trama_analizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 850, 33));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informacion");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 1000, 33));

        txt_s_trama.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_s_trama.setForeground(new java.awt.Color(102, 102, 102));
        txt_s_trama.setText("Escriba la trama...");
        txt_s_trama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_s_trama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_s_tramaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_s_tramaFocusLost(evt);
            }
        });
        jPanel1.add(txt_s_trama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 930, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("Trama:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 40));

        btn_agregar.setBackground(new java.awt.Color(255, 255, 255));

        txt_agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icono_agregar.png"))); // NOI18N
        txt_agregar.setToolTipText("adjunte archivo de texto");
        txt_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_agregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_agregarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_agregarLayout = new javax.swing.GroupLayout(btn_agregar);
        btn_agregar.setLayout(btn_agregarLayout);
        btn_agregarLayout.setHorizontalGroup(
            btn_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_agregarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_agregarLayout.setVerticalGroup(
            btn_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_agregarLayout.createSequentialGroup()
                .addComponent(txt_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 50, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 159, 199)));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setText("Ethertype:");

        txt_mac_destino.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_mac_destino.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_mac_destino.setText("N/D");

        txt_mac_origen.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_mac_origen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_mac_origen.setText("N/D");

        txt_ethertype.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_ethertype.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_ethertype.setText("N/D");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setText("Direccion MAC(origen):");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setText("Direccion MAC(Destino):");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mac_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ethertype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mac_destino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mac_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mac_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ethertype, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 159, 199)));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setText("Direccion IP(Destino):");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setText("Direccion IP(origen):");

        txt_ip_origen.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_ip_origen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_ip_origen.setText("N/D");

        txt_ip_destino.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_ip_destino.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_ip_destino.setText("N/D");

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel9.setText("Puerto(Origen):");

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setText("Puerto(Destino):");

        txt_puerto_origen.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_puerto_origen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_puerto_origen.setText("N/D");

        txt_puerto_destino.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_puerto_destino.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_puerto_destino.setText("N/D");

        txt_protocolo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_protocolo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_protocolo.setText("N/D");

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel14.setText("Protocolo:");

        txt_ttl.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_ttl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_ttl.setText("N/D");

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel15.setText("TTL:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_puerto_destino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ip_origen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ip_destino, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_protocolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_puerto_origen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ttl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ip_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ip_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ttl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_protocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_puerto_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_puerto_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1080, 320));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo_Redes.png"))); // NOI18N
        jLabel11.setText(" Analizador de tramas");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 890, 140));

        btn_procesar.setBackground(new java.awt.Color(46, 159, 199));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Procesar");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_procesarLayout = new javax.swing.GroupLayout(btn_procesar);
        btn_procesar.setLayout(btn_procesarLayout);
        btn_procesarLayout.setHorizontalGroup(
            btn_procesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_procesarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_procesarLayout.setVerticalGroup(
            btn_procesarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_procesarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btn_procesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 170, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        btn_cerrar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_cerrarLayout = new javax.swing.GroupLayout(btn_cerrar);
        btn_cerrar.setLayout(btn_cerrarLayout);
        btn_cerrarLayout.setHorizontalGroup(
            btn_cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );
        btn_cerrarLayout.setVerticalGroup(
            btn_cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 1025, Short.MAX_VALUE)
                .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 40));

        txt_nombre_archivo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_nombre_archivo.setText("N/D");
        jPanel1.add(txt_nombre_archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 290, 30));

        txt_error_trama.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_error_trama.setText("N/D");
        jPanel1.add(txt_error_trama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 380, 30));

        txt_c_trama.setEditable(false);
        txt_c_trama.setBorder(null);
        txt_c_trama.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_c_trama.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_c_trama.setSelectionColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(txt_c_trama);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 790, 90));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/package_106363.png"))); // NOI18N
        jLabel16.setText(" Paquete de red");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 470, 40));

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ethernet_off_4204.png"))); // NOI18N
        jLabel17.setText(" Ethernet");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 480, 40));

        txt_id_destino.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_id_destino.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_id_destino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bluewarningexclamationmark_azul_advertenci_12456.png"))); // NOI18N
        txt_id_destino.setText(" N/D");
        jPanel1.add(txt_id_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 880, 490, 33));

        txt_id_origen.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txt_id_origen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_id_origen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bluewarningexclamationmark_azul_advertenci_12456.png"))); // NOI18N
        txt_id_origen.setText(" N/D");
        jPanel1.add(txt_id_origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 880, 490, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getContentPane().setBackground(this.getBackground());
        txt_error_trama.setVisible(false);
        txt_nombre_archivo.setVisible(false);
        txt_id_origen.setVisible(false);
        txt_id_destino.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void txt_s_tramaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_s_tramaFocusGained
        txt_s_trama.setForeground(Color.BLACK);
        if(txt_s_trama.getText().equalsIgnoreCase("Escriba la trama..."))
        {
            txt_s_trama.setText("");
        }
    }//GEN-LAST:event_txt_s_tramaFocusGained

    private void txt_s_tramaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_s_tramaFocusLost
        if(txt_s_trama.getText().isEmpty())
        {
            txt_s_trama.setText("Escriba la trama...");
            txt_s_trama.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_s_tramaFocusLost

    private void txt_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_agregarMouseEntered
        btn_agregar.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_txt_agregarMouseEntered

    private void txt_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_agregarMouseExited
        btn_agregar.setBackground(Color.white);
    }//GEN-LAST:event_txt_agregarMouseExited

    private void txt_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_agregarMouseClicked
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fi = new FileNameExtensionFilter("txt", "txt");
        j.setFileFilter(fi);
        j.setSize(new Dimension(1000, 700));
        int se = j.showOpenDialog(null);
        if (se == 0) {
            txt_nombre_archivo.setVisible(true);
            txt_nombre_archivo.setText("Archivo Leido: " + j.getSelectedFile().getName());
            ruta_archivo = j.getSelectedFile().getAbsolutePath();
            leer_archivo();
        } else {
        }
    }//GEN-LAST:event_txt_agregarMouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
       btn_cerrar.setBackground(Color.red);
       jLabel13.setForeground(Color.white);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        btn_cerrar.setBackground(Color.white);
        jLabel13.setForeground(Color.black);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        if(txt_s_trama.getText().isEmpty() == true && txt_c_trama.getText().isEmpty() == true)
        {
            txt_error_trama.setVisible(true);
            txt_error_trama.setText("*Ingrese o seleccione una trama");
            txt_error_trama.setForeground(Color.red);
        }else if(txt_s_trama.getText().isEmpty() == true)
        {
            analizar_trama(txt_c_trama.getText());
        }else
        {
            analizar_trama(txt_s_trama.getText());
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        btn_procesar.setBackground(new Color(129, 202, 226));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        btn_procesar.setBackground(new Color(46, 159, 199));
    }//GEN-LAST:event_jLabel12MouseExited
    
    private String type(String bytes)
    {
        Map<String, String> map = new HashMap<>();
        
        map.put("0800","IPv4");
        map.put("86dd","IPv6");
        map.put("0806","ARP");
        map.put("8100", "VLAN");
        map.put("88cc","LLDP");
        map.put("8137", "IPX");
        map.put("8808", "EAPOL");
        map.put("0835", "RARP");
        map.put("0814", "SNMP");
        map.put("880b", "PPP");
        map.put("88c7", "Autenticación 802.11 wifi");
        
        return map.get(bytes);
    }
    
    private String protocolos(int bytes)
    {
        Map<Integer, String> map = new HashMap<>();
        
        map.put(1,"ICMP");
        map.put(2,"IGMP");
        map.put(3,"GGP");
        map.put(4,"IP");
        map.put(5,"ST");
        map.put(6,"TCP");
        map.put(7,"EGP");
        map.put(8,"IGP");
        map.put(9,"BBN-RCC-MON");
        map.put(10,"NVP-II");
        map.put(11,"PUP");
        map.put(12,"ARGUS");
        map.put(13,"EMCON");
        map.put(14,"XNET");
        map.put(15,"CHAOS");
        map.put(17,"UDP");
        map.put(18,"DCN-MEAS");
        map.put(18,"");
        map.put(19,"HMP");
        map.put(20,"PRM");
        map.put(21,"XNS-IDP");
        map.put(22,"TRUNK-1");
        map.put(23,"TRUNK-2");
        map.put(24,"LEAF-1");
        map.put(25,"LEAF-2");
        map.put(26,"RDP");
        map.put(27,"IRTP");
        map.put(28,"ISO-TP4");
        map.put(29,"NETBLT");
        map.put(30,"MFE-NSP");
        map.put(31,"MERIT-INP");
        map.put(32,"DCCP");
        map.put(33,"3PC");
        map.put(34,"IDPR");
        map.put(35,"XTP");
        map.put(36,"DDP");
        map.put(37,"IDPR-CMTP");
        map.put(38,"TP++");
        map.put(39,"IL");
        map.put(40,"IPv6");
        map.put(41,"SDRP");
        map.put(42,"IPv6-ROUTE");
        map.put(43,"IPv6-Frag");
        map.put(44,"IDRP");
        map.put(45,"IDRP");
        map.put(46,"RSVP");
        map.put(47,"DSR");
        map.put(48,"BNA");
        map.put(49,"ESP");
        map.put(50,"AH");
        map.put(51,"I-NLSP");
        map.put(52,"SWIPE");
        map.put(53,"NARP");
        map.put(54,"MOBILE");
        map.put(55,"TLSP");
        map.put(56,"SKIP");
        map.put(57,"IPv6-ICMP");
        map.put(58,"IPv6-NoNXT");
        map.put(59,"Opts");
        map.put(60,"HostInternal");
        map.put(61,"CFTP");
        map.put(62,"LocalNetwork");
        map.put(63,"SAT-EXPAK");
        map.put(64,"KRYPTOLAN");
        map.put(65,"RVD");
        map.put(66,"IPPC");
        map.put(67,"SAT-MON");
        map.put(68,"VISA");
        map.put(69,"IPCV");
        map.put(70,"CPNX");
        map.put(71,"CPHB");
        map.put(72,"WSP");
        map.put(73,"PVP");
        map.put(74,"BR-SAT-MON");
        map.put(75,"SUN-ND");
        map.put(76,"WB-MON");
        map.put(77,"WB-EXPACK");
        map.put(78,"ISO-IP");
        map.put(79,"VMTP");
        map.put(80,"SECURE-VMTP");
        map.put(81,"VINES");
        map.put(82,"TTP");
        map.put(83,"NSFNET-IGP");
        map.put(84,"DGP");
        map.put(85,"TCF");
        map.put(86,"EIGRP");
        map.put(87,"OSPFIGP");
        map.put(88,"Sprite-RPC");
        map.put(89,"LARP");
        map.put(90,"MTP");
        map.put(91,"AX.25");
        map.put(92,"IPIP");
        map.put(93,"MICP");
        map.put(94,"SCC-SP");
        map.put(95,"ETHERIP");
        map.put(96,"ENCAP");
        map.put(97,"GMTP");
        map.put(98,"IFMP");
        map.put(99,"PNMI");
        map.put(100,"PIM");
        map.put(101,"ARIS");
        map.put(102,"SCPS");
        map.put(103,"QNX");
        map.put(104,"A/N");
        map.put(105,"IPcomp");
        map.put(106,"SNP");
        map.put(107,"Compaq-Peer");
        map.put(108,"IPX-in-IP");
        map.put(109,"VRRP");
        map.put(110,"PGM");
        map.put(121,"SMP");
        map.put(122,"SM");
        map.put(123,"PTP");

        return map.get(bytes);
    }
    
    private String PuertoEspecial(int bytes){
    
     Map<Integer, String> map  = new HashMap<>();

        map.put(20, "FTP");
        map.put(21, "FTP");
        map.put(22, "SSH");
        map.put(23, "TELNET");
        map.put(25, "SMTP");
        map.put(53, "DNS");
        map.put(67, "UDP servidor");
        map.put(68, "UDP inicio");
        map.put(69, "UDP transferencia");
        map.put(80, "HTTP");
        map.put(110, "POP3");
        map.put(123, "TCP");
        map.put(143, "IMAP");
        map.put(443, "HTTPS");
        map.put(445, "SMB");
        map.put(993, "IMAP");
        map.put(995, "POP3");
        map.put(2049, "NFS");
        map.put(3306, "MYSQL");
        map.put(3389, "RDP");
    
        return map.get(bytes);
    }
    
    private String identificador_puerto(int x)
    {
        String txt = "";
        String puerto = PuertoEspecial(x);
        if(puerto == null)
        {
            txt = "El puerto "+x+" fue generado aleatoriamente";
        }else if(puerto.equals("FTP"))
        {
            txt = "El puerto "+x+" puede ser de un servidor FTP";
        }else if(puerto.equals("SSH"))
        {
            txt = "El puerto "+x+" puede ser de un servidor de sesion remota SSH";
        }else if(puerto.equals("TELNET"))
        {
            txt = "El puerto "+x+" puede ser de un servidor de sesion remota TELNET";
        }else if(puerto.equals("SMTP"))
        {
            txt = "El puerto "+x+" puede ser de un servidor SMTP";
        }else if(puerto.equals("DNS"))
        {
            txt = "El puerto "+x+" puede ser de un servidor DNS";
        }else if(puerto.equals("HTTP"))
        {
            txt = "El puerto "+x+" puede ser de un servidor web HTTP";
        }else if(puerto.equals("POP3"))
        {
            txt = "El puerto "+x+" puede ser de un servidor POP3";
        }else if(puerto.equals("IMAP"))
        {
            txt = "El puerto "+x+" puede ser de un servidor IMAP";
        }else if(puerto.equals("HTTPS"))
        {
            txt = "El puerto "+x+" puede ser de un servidor web HTTPS";
        }else if(puerto.equals("NFS"))
        {
            txt = "El puerto "+x+" puede ser de un servidor NFS";
        }else if(puerto.equals("MYSQL"))
        {
            txt = "El puerto "+x+" puede ser de un servidor de base de datos MYSQL";
        }else if(puerto.equals("RDP"))
        {
            txt = "El puerto "+x+" puede ser de un servidor de sesion remota RDP";
        }else if(puerto.equals("UDP servidor"))
        {
            txt = "El puerto "+x+" puede ser de un servidor bajo protocolo de inicio UDP";
        }else if(puerto.equals("UDP cliente"))
        {
            txt = "El puerto "+x+" puede ser de un cliente bajo protocolo de inicio UDP";
        }else if(puerto.equals("UDP transferencia"))
        {
            txt = "El puerto "+x+" puede ser de un servidor de transferencia de archivos con protocolo UDP";
        }else if(puerto.equals("TCP"))
        {
            txt = "El puerto "+x+" puede ser de un servidor bajo el protocolo TCP";
        }
        return txt;
    }
    
    private void analizar_trama(String trama)
    {
        try
        {
            
            String trama2[] = trama.split(" ", trama.length());
            for(int i = 0; i<trama2.length; i++)
            {
                if(trama2[i].equals("") || trama2[i] == null)
                {

                }else
                {
                    int trama1 = Integer.parseInt(trama2[i], 16);
                }
            }
            procesar(trama);
            
        }catch(NumberFormatException ex)
        {
            System.out.print(ex.getMessage());
            txt_error_trama.setVisible(true);
            txt_error_trama.setForeground(Color.red);
            txt_error_trama.setText("*Trama no valida o mal escrita");
        }
    }
    
    private void procesar(String trama1)
    {
        txt_trama_analizada.setText(trama1);
        String[] trama;
        trama = trama1.split(" ", trama1.length());
        
        ArrayList<String> lista_trama = new ArrayList<>();
        for(int i = 0; i < trama.length; i++)
        {
            if(trama[i].equals("") || trama[i] == null)
            {
                
            }else
            {
                lista_trama.add(trama[i]);
            }
        }
           
        String mac_origen = lista_trama.get(0);
        String mac_destino = lista_trama.get(1);
        for(int i = 1; i<6; i++)
        {
            mac_origen = mac_origen+" "+lista_trama.get(i);
        }
        for(int i = 7; i<12; i++)
        {
            mac_destino = mac_destino+" "+lista_trama.get(i);
        }
        String type = lista_trama.get(12);
        for(int i = 13; i<14; i++)
        {
            type = type + lista_trama.get(i);
        }
        
        String ip_origen = "";
        ip_origen = ip_origen + Integer.parseInt(lista_trama.get(26), 16);
        for(int i = 27; i<30; i++)
        {
            ip_origen = ip_origen +"."+ Integer.parseInt(lista_trama.get(i), 16);
        }
        
        String ip_destino = "";
        ip_destino = ip_destino + Integer.parseInt(lista_trama.get(30), 16);
        for(int i = 31; i<34; i++)
        {
            ip_destino = ip_destino +"."+ Integer.parseInt(lista_trama.get(i), 16);
        }
        String puerto_origen = ""+Integer.parseInt(lista_trama.get(34)+lista_trama.get(35), 16);
        String puerto_destino = ""+Integer.parseInt(lista_trama.get(36)+lista_trama.get(37), 16);
        String protocolo = protocolos(Integer.parseInt(lista_trama.get(23), 16));
        String TTL = ""+Integer.parseInt(lista_trama.get(22), 16);
        
        
        txt_mac_origen.setText(mac_destino);
        txt_mac_destino.setText(mac_origen);
        txt_ethertype.setText(type(type));
        txt_ip_origen.setText(ip_origen);
        txt_ip_destino.setText(ip_destino);
        txt_puerto_origen.setText(puerto_origen);
        txt_puerto_destino.setText(puerto_destino);
        txt_protocolo.setText(protocolo);
        txt_ttl.setText(TTL);
        txt_id_origen.setVisible(true);
        txt_id_origen.setText(identificador_puerto(Integer.parseInt(puerto_origen)));
        txt_id_destino.setVisible(true);
        txt_id_destino.setText(identificador_puerto(Integer.parseInt(puerto_destino)));
    }
    
    private void leer_archivo()
    {
        FileReader leer = null;
        try
        {
            File archivo = new File(ruta_archivo);
            leer = new FileReader(archivo);
            BufferedReader bf = new BufferedReader(leer);
            
                try { 
                    String txt = bf.readLine();
                    txt_c_trama.setText(txt);
                }catch (IOException ex) {
                    Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
                }
        }catch(FileNotFoundException ex)
        {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
            
        } finally {
            try {
                leer.close();
            } catch (IOException ex) {
                Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_agregar;
    private javax.swing.JPanel btn_cerrar;
    private javax.swing.JPanel btn_procesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txt_agregar;
    private javax.swing.JTextPane txt_c_trama;
    private javax.swing.JLabel txt_error_trama;
    private javax.swing.JLabel txt_ethertype;
    private javax.swing.JLabel txt_id_destino;
    private javax.swing.JLabel txt_id_origen;
    private javax.swing.JLabel txt_ip_destino;
    private javax.swing.JLabel txt_ip_origen;
    private javax.swing.JLabel txt_mac_destino;
    private javax.swing.JLabel txt_mac_origen;
    private javax.swing.JLabel txt_nombre_archivo;
    private javax.swing.JLabel txt_protocolo;
    private javax.swing.JLabel txt_puerto_destino;
    private javax.swing.JLabel txt_puerto_origen;
    private javax.swing.JTextField txt_s_trama;
    private javax.swing.JLabel txt_trama_analizada;
    private javax.swing.JLabel txt_ttl;
    // End of variables declaration//GEN-END:variables

    private Object setContentPane() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
